# GET http://localhost:3003/target-coordinates

# post
POST  http://localhost:3003/target-coordinates
Content-Type: application/json

{
    "lat":2342323423442343232,
    "lon": 234234234,
    "target": "dasdasdemo"
}